# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PT Strong Sports Rehab
description: PT Strong Sports Rehab - Sports rehab in your own home
url: "https://www.immersography.com"
image: /assets/logo-main.png
twitter: ptstrongsportsrehab
plugins:
  - jekyll-sitemap